# Generated by Django 5.2.8 on 2025-11-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historialcliente_cliente_bloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
