# Generated by Django 5.2.9 on 2025-12-03 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedido_motivo_rechazo_alter_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudConfeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_prenda', models.CharField(choices=[('poleron', 'Polerón'), ('polera', 'Polera'), ('pantalon', 'Pantalón'), ('otro', 'Otro')], max_length=20)),
                ('descripcion_diseno', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('cotizado', 'Cotizado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_confeccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
