# Generated by Django 5.2.9 on 2025-12-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_solicitudconfeccion_observaciones_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudconfeccion',
            name='cotizacion_aceptada',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='solicitudconfeccion',
            name='cotizacion_monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudconfeccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('cotizado', 'Cotizado'), ('rechazado', 'Rechazado'), ('aceptado', 'Aceptado por cliente'), ('cancelado', 'Cancelado por cliente')], default='pendiente', max_length=20),
        ),
    ]
